# Generated by Django 4.1.7 on 2023-05-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_accgame_image_alter_accgame_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accgame',
            name='password',
            field=models.CharField(default='uB6LhGs8', max_length=255),
        ),
        migrations.AlterField(
            model_name='accgame',
            name='username',
            field=models.CharField(default='nHRQPK8CEY', max_length=255),
        ),
    ]
